### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by MuhammadAli987** [hbenbel/Eulerian-Video-Magnification#1]
Hello Sir,
       Hope you are doing good, Can you please update evm.py with comments and examples.

**Comment by MuhammadAli987** [comment]
![image](https://user-images.githubusercontent.com/111043003/188064880-1c037afe-ad4f-4d02-b679-e35811654877.png)

**Comment by hbenbel** [comment]
Hello, if you go in the results folder you can find the configuration that I used to generate the video from the data folder. Also, if you want to launch the code, please read the README for the command to use to do so. If you want more details on how the code works, I invite you to go to my blog where I explain in details the eulerian video magnification algorithm: https://hbenbel.github.io/blog/evm/

Hope this helps :)

**Comment by MuhammadAli987** [comment]
Hello Sir, Thankyou so much, This will help.
