### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Mushimush** [hbenbel/Eulerian-Video-Magnification#2]
evm.py: error: the following arguments are required: --saving_path/-s
[--lambda_cutoff: command not found
[--high_omega: command not found
[--mode: command not found

i can't seem to run it after running the usage, any help is greatly appreciated

**Comment by Mushimush** [comment]
what i did was put this into the terminal : 

    python src/evm.py [-h] --video_path VIDEO_PATH [--level LEVEL] [--alpha ALPHA]
              [--lambda_cutoff LAMBDA_CUTOFF] [--low_omega LOW_OMEGA]
              [--high_omega HIGH_OMEGA] --saving_path SAVING_PATH
              [--mode {gaussian,laplacian}] [--attenuation ATTENUATION]

**Comment by Mushimush** [comment]
python src/evm.py [-h] --video_path data/face.mp4 [--level 4] [--alpha 50]
              [--lambda_cutoff LAMBDA_CUTOFF] [--low_omega 0.8333]
              [--high_omega 1] --saving_path results
              [--mode {gaussian}] [--attenuation 1]

**Comment by hbenbel** [comment]
Hi, an example of execution: python src/evm.py -v data/baby.mp4 -l 2 -a 2 -lo 0.4 -ho 0.8 -s results/test -m gaussian -at 0.5.
You can also execute python src/evm.py --help to see more details about the parameters.

**Comment by Mushimush** [comment]
Hello, Thank you so much for your reply!

I have created a file named results/test, and ran the following command :

python src/evm.py -v data/face.mp4 -l 4 -a 50 -lo 0.833  -s results/test -m
gaussian -at 1

everything runs smoothly except for the saving part. This is the error:

***@***.*** global /io/opencv/modules/videoio/src/cap.cpp (595) open
VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error:
(-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of
file): results/test in function 'icvExtractPattern'


Saving Video:
100%|################################################################################################################################|
301/301 [00:00<00:00, 499.62it/s]

 I am able to solve this problem by renaming the folder results/0test,
everything runs smoothly, but the folder is empty!

How do I solve this?

Best Regards
Stanley

**Comment by hbenbel** [comment]
try results/test.avi, the extension is mandatory in order to have the output video generated

**Comment by Mushimush** [comment]
Hello,

Do you know the main reasons why the gaussian filtering gets killed? I
tried with the parameter that you put in your readme, but the process gets
killed .  How do you know which parameters to tweak, to not get it killed?

Thank you!
